### PR TITLE
Improved Tin_1 unit test

### PR DESCRIPTION
**Pull request by pjanck**
# IFC4.3 Unit test

## Unit test
Tin_1

## Review requested
- removed `IfcBuilding`
- removed coloring
- improved the `readme.md`

**Instruction** to @LeeGregory12d : If you agree with my simplifications / additions, please *approve* this pull request and I will merge it.

### CODE REVIEW

**Comment by LeeGregory12d** [comment]
@pjanck
Stefan
Was there a reason to take out the IfcIndexColourMap or is there a simpler way to say all the triangles in the IfcTriangulatedIrregularNetwork are green ?

**Comment by pjanck** [comment]
Dear Lee,

the reason was simple - to have as little *new* entities as possible. I believe, one first needs to understand geometry - so colour information only burdens at start.

I will leave the colour assignment in another UT of yours, where you have assigned different colours to the TIN. That one will base of this UT, so that the readers can *gradually* implement new features.

**Comment by pjanck** [comment]
Another thought: do you have the TIN available in any other format? So that other exporters can first import the TIN from another source?

**Comment by LeeGregory12d** [comment]
Stefan,
I must admit I have never thought of a Tin without a colour.
I'm not certain how you would display it.

Thanks for deleting the lines from the Ifc file  as I don't have an option to not write out the colour.

**Comment by pjanck** [comment]
Lee,

well, if there is no colour attached to a geometry, it is the viewer's job to default to one. For example, OIP defaults to green for all `IfcGeotechnicalElement`s. Others get blue, gray, whatever.

I assume you agree with the changes made here? It would be great if you can *approve* using the review functionality.

**Review by LeeGregory12d — APPROVED** [review]
Certainly a simple case could have no colour.
But in general I would think having  colour in tins is a great benefit for at least two reasons:
(a) In a normal projects you usually have many tins (even hundreds) so colour helps to visually tell them apart.
      For example, even in the simple Storyline from Finalnd, the LandXML file contained 7 tins virtually on top of each other  and so hard to differentiate (Saven ap, Kaivanto, Kantava kerros, Kuivatus,  Ylin yhd pinta, Jakava kerros and Alin rak pinta, 
(b) For the one tin, using different colours for different areas is extremely useful.
      For example in a design tin, having cut and fill areas in different colours, showing different  pavement areas in different colours etc

**Comment by LeeGregory12d** [comment]
The Approve has been done.

Regards
Lee

Dr Lee Gregory
Managing Director
12D Solutions Pty Ltd

Creators of the 12d Model Civil and Surveying Software
and 12d Synergy for Data Management and Project Collaboration.
Ph: +61 (0)2 9970 7117
Email: lee.gregory@12d.com<mailto:lee.gregory@12d.com>
Web: www.12d.com<http://www.12d.com/aus/?utm_source=emailsig&utm_medium=email&utm_campaign=emaillink>

**Comment by pjanck** [comment]
Lee, thank you for accepting. 

I understand your points in assigning colour information to pass different classifications etc. to different TINs or its elements. You are very welcome to do that in your exports. I've just manipulated your example in order to reduce the starting complexity when software vendors not yet supporting TINs wish to start implementing them.

**Pull request merged**
