### PR TITLE
Enabling ifc4x3 as text

### PR DESCRIPTION
**Pull request by pjanck**
## Changes and improvements proposed by this pull request
Disabled LFS for 4x3 files. These should be small and atomic, as well as the changes across versions should be observable without a problem.

## TODOs after merge
- The example file added to the root folder of 4x3 should be deleted. It was added to prove a point.
- The files already within 4x3 folder should be reuploaded.

### CODE REVIEW

**Comment by pjanck** [comment]
Testing Slack integration. Ignore this comment.

**Comment by pjanck** [comment]
I'm waiting another day for reviews, afterwards I'll merge this.

**Comment by berlotti** [comment]
Suggest to use a dot for versioning IFC. It seems we are using 4.1, 4.2, 4.3 instead of the 'x' ever since IFC4.
(the x was short for 'extension'... IFC2x3 was the third extension of IFC2. IFC4 was actually IFC2x4, but it was decided to use 'normal' version numbers from that point on)

**Comment by TLiebich** [comment]
not sure, that using "." instead of "x" means in this context?

Officially, there was the decision to use a "." in the official naming of "point" releases based on IFC4 quite a while ago (6..7 years). However a "." (dot) is not allowed as character within a schema name following ISO 10303-21 (the STEP file format that is used for *.ifc files). Therefore the use of "x" remains to be valid for the EXPRESS schema name designator.

so the line in an IFC file has to remain as:
FILE_DESCRIPTION(('IFC4X1'),'2;1'); --> IFC4.1
FILE_DESCRIPTION(('IFC4X3_RC1'),'2;1'); --> IFC4.3 RC1

**Pull request merged**
