### PR TITLE
UT_Alignment_12d_2

### PR DESCRIPTION
**Pull request by LeeGregory12d**
## Unit test
New UT with left arc in HG and crest arc in VG - semantics only

## Review requested
@pjanck

### CODE REVIEW

**Review by TLiebich — COMMENTED** [review]
see some minor issues below.

**Comment by larswik** [comment]
Right now it seems as if the uploaded file contains things like "<<<<<<< Updated upstream" etc. Can you please upload the alignment file?

**Comment by larswik** [comment]
File looks good now!

**Review by larswik — APPROVED** [review]

**Comment by LeeGregory12d** [comment]
UT redone in repository IFC-infra-unit-test

**Pull request closed without merging**
