### PR TITLE
Georeferencing tin 1

### PR DESCRIPTION
**Pull request by LeeGregory12d**
# IFC4.3 Unit test

## Unit test
Tin in map coordinates

## Review requested
- using IfcProjectedCRS and IfcMapConversion
- 

@pjanck

### CODE REVIEW

**Comment by TLiebich** [comment]
the IfcMapConversion does not have Eastings and Northings set (or none-zero Value). Normals of triangles all show downwards.

**Comment by LeeGregory12d** [comment]
Thomas,
1. IfcMapConversion
The ifc file has a IfcProjectedCRS and for that situation we were automatically writing out a IfcMapConversion as well.

For this particular case, the IfcMapConversion is just a unity transformation (ie no translation in (x,y,z) ,no 2D rotation, and scale is 1). That is, IfcMapConversion does nothing.

So for the "do nothing" case, we should always leave out the ifcMapConversion ?

2. Normal for triangles
I'll chase that up.

**Comment by TLiebich** [comment]
to 1) please always keep the IfcMapConversion, my question (also to the whole IfcRoad deployment team) is, whether it should be legal to have such big offsets (>1000km) between the model origin and the coordinates of the geometry, knowing that this causes issues in BIM software (loss of precision for 3D volumetric operations). E.g. in Revit, the geometry shall not be more then ca. 20km away from the origin.

**Comment by pjanck** [comment]
1) I think we need to agree to use `IfcMapConversion` whenever possible to diminish the geometric coordinates - having a *translating vector* to the local construction site should be always used (with optional rotation if the site is rotated as compared to the underlying `IfcProjectedCRS`). This should be used even if that site is *n* kilometers long and/or if a *project base point* is not decided upon --> pick a point in the middle of the model - so as to have geometries spanning from *-n/2* to *n/2*. There should never be a "do nothing" case in order to support all importers :) I think this would be a good candidate for a new "implementors agreement".

Tip to @LeeGregory12d : 
1. *check out* the branch `Georeferencing_Tin_1` on your machine, 
2. *overwrite* the `IFC` file, 
3. *commit* the changes to the file (on the same branch)
4. *push* the newly committed changes.
5. the changes will be added automatically to this *pull request* (no action needed).

**Comment by LeeGregory12d** [comment]
For 1.
(a) Eastings and Northings
I can only speak from my experience but I don't know of any linear infrastructure or surveying software that does work with full Eastings and Northings. Certainly in the eighties some software only ran on Microsoft DOS and because DOS was only 16-bit, that software often only worked with truncated grids> But such software disappeared in the early nineties.

I'm not certain what software suffers from size restrictions or loss of precision but that is **a software limitation** and **NOT** an ifc problem. 

(b) Project Base Point
There are times when we have to write out data with a false origin (project base point) and ifcMapConversion would be used for that. **BUT** it is a very dangerous practice as every user of the data must be made aware of the values of such (x, y, z) offsets so that any such data can be used with GPS systems, or combined with data from other areas, or even to be recombined in the future.  

I'm not certain what an "implementers agreement" is and where that fits into ifc but I can't imagine any infrastructure software wanting such a restriction.

(c) Local Engineering Coordinates
Have a false origin should not be confused with converting between (Eastings, Northings, Heights) and  "local engineering coordinates". This does have (x,y,z) offsets but it will also involve a scale factor being applied to the X and Y, AND the scale factor is often not equal to one. Plus the size of the area being considered should only span a few kilometers in length and only hundreds of metres  in height differences otherwise the scale factor will start to vary from a constant value.

IfcMapConversion can be used in this case as long as the scale factor in ifcMapConversion only applies to x and y and not to z, and the data range is restricted.

(d) Typical Infrastructure projects such as roads and rail which have a number of areas with different "local engineering coordinates"
I don't think this case is covered by ifc 4x3 RC1 as I believe IfcMapConversion applies to all the data in the ifc file and a different (x,y) scale factor would be needed for each "local engineering coordinate" area.

**Comment by LeeGregory12d** [comment]
Thomas,
2. Normals for triangles in tin
I've updated the ifc file and the triangles should now all be anticlockwise and hence the normals pointing upwards

**Comment by TLiebich** [comment]
Gregory,

coming back to your general remarks - I think, they are worth to be discussed, but on a more general platform, e.g. the buildingSMART Forum. Its relevance goes beyond this UC. Briefly:

to a). understood, but the issue comes from the Solid modeling gemetric kernels, where a much higher precision is required. E.g. in Revit, you have a proposed 25km range, in CATIA it was a square of 1km in the past (not higher, but not in the scale needed here). Its about the precision under which faces are still considered co-planar, etc. - all needed for Boolean operations.

to c). we need to get an agreement abot scaling (currently not well defined in IfcMapProjection) - completely agreed

to d). to me, it is out of scope (but not sure about the view of others). In scope should be to exchange information about one infrastructure works (e,g. a bridge(s)) within a notably restricted area (arbitrary 50km max ???)

but as said above, this requires a broader discussion.

 
> 
> For 1.
> (a) Eastings and Northings
> I can only speak from my experience but I don't know of any linear infrastructure or surveying software that does not work with full Eastings and Northings. Certainly in the eighties some software ran on Microsoft DOS and because DOS was only 16-bit, that software often only worked with truncated grids. But such software disappeared in the early nineties.
> 
> I'm not certain what software suffers from size restrictions or loss of precision but that is **a software limitation** and **NOT** an ifc limitation.
> 
> (b) Project Base Point
> There are times when we have to write out data with a false origin (project base point) and ifcMapConversion could be used for that. **BUT** it is a very dangerous practice as every user of the data must be made aware of the values of such (x, y, z) offsets so that any such data can be used with GPS systems, or combined with data from other areas, or even to be recombined in the future.
> 
> I'm not certain what an "implementers agreement" is and where that fits into ifc but I can't imagine any infrastructure software wanting such a restriction.
> 
> (c) Local Engineering Coordinates
> Have a false origin should not be confused with converting between (Eastings, Northings, Heights) and "local engineering coordinates". This does have (x,y,z) offsets but it will also involve a scale factor being applied to the X and Y, AND the scale factor is often not equal to one. Plus the size of the area being considered should only span a few kilometers in length and only hundreds of metres in height differences otherwise the scale factor will start to vary from a constant value.
> 
> IfcMapConversion can be used in this case as long as the scale factor in ifcMapConversion only applies to x and y and not to z, and the data range is restricted.
> 
> (d) Typical Infrastructure projects such as roads and rail which have a number of areas with different "local engineering coordinates"
> I don't think this case is covered by ifc 4x3 RC1 as I believe IfcMapConversion applies to all the data in the ifc file and a different (x,y) scale factor would be needed for each "local engineering coordinate" area.

**Comment by LeeGregory12d** [comment]
Thanks Thomas.
I am happy for these issues to be discussed on a more general forum. 
Just let me know which one you think is the most appropriate.

(a) yes it does appear that many of the perceived limits have nothing to do with ifc's but stem from the limitations of some software that may never have been designed to work for large scale infrastructure.  

But please, don't handicap the tremendous potential of ifc's for infrastructure because of the current weakness of some software.

**Comment by SergejMuhic** [comment]
All of these issues seem to be connected and could be solved with allowing "multiple areas with local engineering coordinates". We already have a mechanism in the schema (would need a bit of a rework) for setting geometry in context. An IfcProject can have multiple and each of them can have its own IfcCoordinateOperation i.e. IfcMapConversion. It is a bit of a problem that the locations cannot reference the context, only IfcShapeRepresentation can. We are exploring this in the paper @pjanck proposed.

**Comment by LeeGregory12d** [comment]
Thanks Sergej.
I look forward to seeing your proposal.

**Pull request merged**
